### Car Price Scraping

In [1]:
#importing libraries
from selenium import webdriver
import time
import pandas as pd
import numpy as np
import urllib
import os
import sys

In [79]:
#initialize web driver
driver = webdriver.Chrome(executable_path = r"C:\Users\DEVASREE\Downloads\chromedriver.exe")
url = "https://www.olx.in/cars_c84"
driver.get(url)
time.sleep(3)

In [6]:
#initialize lists
urls = []
cities = []

In [71]:
#looping through different locations for getting urls of cars
locations = ["Bengaluru", "Delhi", "Mumbai", "Chennai", "Hyderabad", "Kochi", "Kozhikode", "Kolkata",\
             "Coimbatore", "Goa", "jaipur", "Chandigarh"]
for lc in locations:
    time.sleep(5)
    location = driver.find_element_by_class_name("_2xvhw")
    location.clear()
    time.sleep(3)
    location.send_keys(lc)
    time.sleep(5)
    try:
        loc_click = driver.find_element_by_class_name("_1jtbH")
        loc_click.click()
        #load more data
        for i in range(7):
            time.sleep(5)
            driver.find_elements_by_class_name("rui-3evoE")[-1].click()
        
    except Exception as e:
        continue
    lis = driver.find_elements_by_class_name("EIR5N")
    for li in lis:
        urls.append(li.find_element_by_tag_name("a").get_attribute("href"))
        cities.append(lc)

In [7]:
#creating a dataframe and saving it as csv in case of kernal restart or any dataloss
olx = pd.DataFrame({"city":cities, "url": urls})

In [17]:
olx

,Unnamed: 0,city,url
0,0,Bengaluru,https://www.olx.in/item/mercedes-benz-e-class-...
1,1,Bengaluru,https://www.olx.in/item/hyundai-elite-i20-asta...
2,2,Bengaluru,https://www.olx.in/item/volkswagen-ameo-2016-p...
3,3,Bengaluru,https://www.olx.in/item/maruti-suzuki-omni-5-s...
4,4,Bengaluru,https://www.olx.in/item/maruti-suzuki-swift-dz...
...,...,...,...
3595,3595,Chandigarh,https://www.olx.in/item/maruti-suzuki-esteem-2...
3596,3596,Chandigarh,https://www.olx.in/item/xuv-500-automatic-iid-...
3597,3597,Chandigarh,https://www.olx.in/item/mahindra-xuv500-2016-i...
3598,3598,Chandigarh,https://www.olx.in/item/maruti-suzuki-celerio-...
3599,3599,Chandigarh,https://www.olx.in/item/ford-ecosport-2014-die...

In [56]:
#initilize lists for the vehicle info
brands = []
models = []
varient = []
mf_years = []
dr_kms = []
fuel_types = []
no_owners = []
locations = []
transmissions = []
prices = []

In [57]:
#looping through the each url to get car data
for i in range(len(olx["city"])):
    url = olx["url"][i]
    driver.get(url)
    time.sleep(5)
    try:
        det = driver.find_elements_by_class_name("_2vNpt")
        br = det[0].text
        mo = det[1].text
        var = det[2].text
        mf = det[3].text
        fu = det[4].text
        tn = det[5].text
        km = det[6].text
        ow = det[7].text
        price = driver.find_element_by_class_name("_2xKfz").text
        brands.append(br)
        models.append(mo)
        varient.append(var)
        mf_years.append(mf)
        fuel_types.append(fu)
        transmissions.append(tn)
        dr_kms.append(km)
        no_owners.append(ow)
        prices.append(price)
        locations.append(olx["city"][i])
    except Exception as e:
        continue

TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.003
  (Session info: chrome=92.0.4515.159)

In [60]:
#create a df and save as csv for future use(in case of loss)
olxdf = pd.DataFrame({"brand":brands,"model":models, "varient":varient,"mf_year":mf_years, "dr_kms":dr_kms,\
              "fuel_type":fuel_types,"no_of_owners":no_owners,"location":locations, \
              "transmission":transmissions,"price":prices})

In [61]:
olxdf.to_csv("olxdf.csv")

In [2]:
#initialize web driver
driver = webdriver.Chrome(executable_path = r"C:\Users\DEVASREE\Downloads\chromedriver.exe")
url = "https://www.cars24.com"
driver.get(url)
time.sleep(3)

In [21]:
#initialize lists
urls_24 = []
locs = []

In [22]:
#looping through different locations for getting urls of cars
locations = ["bengaluru", "chennai", "new-delhi", "mumbai", "pune", "hyderabad", "kolkata", "ahmedabad",\
             "jaipur", "chandigarh"]
for lc in locations:
    url = "https://www.cars24.com/buy-used-cars-" + lc
    driver.get(url)
    time.sleep(5)
    for i in range(14):
        driver.execute_script("window.scrollTo(0, (document.body.scrollHeight)*.9);")
        time.sleep(5)
    divs = driver.find_elements_by_class_name("_9Ue0B")
    for div in divs:
        urls_24.append(div.get_attribute("href"))
        locs.append(lc)

In [25]:
c24 = pd.DataFrame({"city":locs, "url": urls_24})

In [218]:
brands = []
models = []
varient = []
mf_years = []
dr_kms = []
fuel_types = []
no_owners = []
locations = []
transmissions = []
prices = []

In [219]:
c24 = pd.read_csv("c24.csv")

In [220]:
#looping through the each url to get car data
for i in range(len(c24["city"])):
    url = c24["url"][i]
    driver.get(url)
    time.sleep(5)
    try:
        price = driver.find_elements_by_class_name("_2yYvS")[0].text
        title = driver.find_element_by_class_name("_2geSF").text.split()
        br = title[1]
        mo = title[2]
        var = " ".join(driver.find_element_by_class_name("_18vo2").text.split()[0:-1])
        mf = title[0]
        elem = driver.find_elements_by_class_name("_1-PH2")
        fu = elem[3].text
        tn = elem[5].text
        km = elem[2].text
        ow = elem[1].text
        brands.append(br)
        models.append(mo)
        varient.append(var)
        mf_years.append(mf)
        fuel_types.append(fu)
        transmissions.append(tn)
        dr_kms.append(km)
        no_owners.append(ow)
        prices.append(price)
        locations.append(c24["city"][i])
    except Exception as e:
        continue

In [221]:
#create a df and save as csv for future use(in case of loss)
c24df = pd.DataFrame({"brand":brands,"model":models, "varient":varient,"mf_year":mf_years, "dr_kms":dr_kms,\
              "fuel_type":fuel_types,"no_of_owners":no_owners,"location":locations, \
              "transmission":transmissions,"price":prices})

In [222]:
c24df

,brand,model,varient,mf_year,dr_kms,fuel_type,no_of_owners,location,transmission,price
0,Maruti,Eeco,5 STR WITH AC PLUSHTR,2015,"15,107 km",Petrol,1st Owner,bengaluru,MANUAL,"â‚¹3,80,899"
1,Maruti,Alto,VXI,2011,"38,847 km",Petrol,2nd Owner,bengaluru,MANUAL,"â‚¹2,48,299"
2,Maruti,Alto,LXI,2009,"38,264 km",Petrol,1st Owner,bengaluru,MANUAL,"â‚¹2,55,399"
3,Hyundai,Eon,MAGNA PLUS,2014,"15,628 km",Petrol,1st Owner,bengaluru,MANUAL,"â‚¹3,45,899"
4,Maruti,Alto,LXI,2010,"32,291 km",Petrol,1st Owner,bengaluru,MANUAL,"â‚¹2,31,799"
...,...,...,...,...,...,...,...,...,...,...
2599,Hyundai,i20,MAGNA 1.4 CRDI,2012,"60,022 km",Diesel,1st Owner,chandigarh,MANUAL,"â‚¹2,68,099"
2600,Maruti,Celerio,VXI AMT,2016,"24,250 km",Petrol,1st Owner,chandigarh,AUTOMATIC,"â‚¹3,71,099"
2601,Maruti,Alto,LXI,2019,"1,370 km",Petrol,1st Owner,chandigarh,MANUAL,"â‚¹3,15,999"
2602,Maruti,Swift,VDI ABS,2015,"44,379 km",Diesel,1st Owner,chandigarh,MANUAL,"â‚¹4,47,799"
2603,Honda,Amaze,1.2 EMT I VTEC,2013,"53,024 km",Petrol,3rd Owner,chandigarh,MANUAL,"â‚¹3,51,299"

In [223]:
c24df.to_csv("c24df1.csv")

In [123]:
urls = []
cities = []

In [124]:
#getting urls from cardekho
locations = ["kozhikode", "bengaluru", "ahmedabad", "chennai", "delhi-ncr", "gurgaon", "hyderabad", "jaipur", "kolkata",\
             "mumbai", "new-delhi", "noida", "pune"]
for lc in locations:
    url = "https://www.cardekho.com/used-cars+in+" + lc
    driver.get(url)
    time.sleep(5)
    j=1
    for i in range(25):
        time.sleep(5)
        driver.execute_script("window.scrollTo(0, (document.body.scrollHeight)*.1*"+str(j)+");")
        if j == 9:
            j = 7
        j += 1
        time.sleep(5)
    divs = driver.find_elements_by_class_name("carsName")
    for div in divs:
        urls.append(div.find_element_by_tag_name("a").get_attribute("href"))
        cities.append(lc)

In [126]:
cdekho = pd.DataFrame({"city":cities, "url": urls})

In [127]:
cdekho.to_csv("cdekho.csv")

In [202]:
brands = []
models = []
varient = []
mf_years = []
dr_kms = []
fuel_types = []
no_owners = []
locations = []
transmissions = []
prices = []

In [ ]:
#getting info from cardekho
for i in range(len(cdekho["city"])):
    url = cdekho["url"][i]
    time.sleep(5)
    try:
        price = driver.find_element_by_class_name("amount").text
        title = driver.find_element_by_class_name("vdp-head").find_elements_by_tag_name("h1")
        mf = title[0].text
        br = title[1].text.split()[0]
        mo = title[1].text.split()[1]
        var = " ".join(driver.find_element_by_class_name("vdp-head").text.split()[2:])
        elem = driver.find_elements_by_class_name("iconDetail")
        fu = elem[4].text
        tn = elem[5].text
        km = elem[2].text
        ow = elem[3].text
        
        brands.append(br)
        models.append(mo)
        varient.append(var)
        mf_years.append(mf)
        fuel_types.append(fu)
        transmissions.append(tn)
        dr_kms.append(km)
        no_owners.append(ow)
        prices.append(price)
        locations.append(cdekho["city"][i])
    except:
        try:
            price = driver.find_element_by_class_name("priceSection").text
            title = driver.find_element_by_xpath("//div[@class='variant-name']/preceding::h1").text.split()
            br = title[1]
            if len(title) == 3:
                mo = title[2]
            else:
                mo = ""
            var = driver.find_element_by_class_name("variant-name").text
            mf = title[0]
            det = driver.find_elements_by_class_name("overviewCArd")[0] 
            main = det.find_elements_by_class_name("fontweight500")
            fu = main[2].text
            tn = main[7].text
            km = main[3].text
            ow = main[5].text
            brands.append(br)
            models.append(mo)
            varient.append(var)
            mf_years.append(mf)
            fuel_types.append(fu)
            transmissions.append(tn)
            dr_kms.append(km)
            no_owners.append(ow)
            prices.append(price)
            locations.append(cdekho["city"][i])
        except Exception as e:
            continue

In [204]:
cdekhodf = pd.DataFrame({"brand":brands,"model":models, "varient":varient,"mf_year":mf_years, "dr_kms":dr_kms,\
              "fuel_type":fuel_types,"no_of_owners":no_owners,"location":locations, \
              "transmission":transmissions,"price":prices})

In [206]:
cdekhodf.to_csv("cdekhodf.csv")

In [12]:
#concat data from three websites
data = pd.concat([olxdf, c24df, cdekhodf], axis=0)

In [13]:

data

,Unnamed: 0,brand,model,varient,mf_year,dr_kms,fuel_type,no_of_owners,location,transmission,price
0,0,Hyundai,Elite i20,Asta 1.2,2015,"72,000 km",Petrol,1st,Bengaluru,Manual,"â‚¹ 6,25,000"
1,1,Maruti Suzuki,Omni,5 Seater,2017,"24,000 km",Petrol,2nd,Bengaluru,Manual,"â‚¹ 2,90,000"
2,2,Maruti Suzuki,Swift Dzire,VDI,2017,"91,000 km",Diesel,1st,Bengaluru,Manual,"â‚¹ 7,10,000"
3,3,Skoda,Rapid,1.5 TDI Manual active ambition style,2012,"86,000 km",Diesel,2nd,Bengaluru,Manual,"â‚¹ 4,15,000"
4,4,Maruti Suzuki,Wagon R,LXI,2014,"66,000 km",Petrol,1st,Bengaluru,Manual,"â‚¹ 3,95,000"
...,...,...,...,...,...,...,...,...,...,...,...
1369,1369,Maruti,Swift,ZDI,2015,"83,000 kms",Diesel,First Owner,pune,Manual,6.15 Lakh*
1370,1370,Hyundai,i20,Petrol CVT Asta,2018,"17,908 Kms",Petrol,1st Owner,pune,Automatic,"â‚¹ 7,65,500"
1371,1371,Maruti,Vitara,Brezza ZDi,2018,"43,089 kms",Diesel,First Owner,pune,Manual,9.2 Lakh*
1372,1372,Hyundai,i20,Sportz 1.2,2013,"52,230 kms",Petrol,First Owner,pune,Manual,4.45 Lakh*
1373,1373,Maruti,Ertiga,ZXI,2013,"81,000 kms",Petrol,First Owner,pune,Manual,5.95 Lakh*

In [14]:
data = data.iloc[: , 1:]

In [16]:
#save as csv
data.to_csv("car_price.csv")